### PR TITLE
add a --debug-state command-line option

### PR DESCRIPTION
**Pull request by meejah**
This exposes set_trace functionality for debugging
state-machine transitions in the various state machines.

### CODE REVIEW

**Comment by piegamesde** [comment]
**BIKESHED** Why don't you call the flag "verbose" or something more common? There's no need to restrict trace level messages to those that somehow inform about state changes.

**Comment by meejah** [comment]
`set_trace` is an Automat method; these aren't "trace"-level log messages, they're specifically for tracing the state-transitions of the various state-machines (so are very unlikely to be useful to non-developers .. is why I hid it behind a thing starting with `--debug` ...)

**Review by piegamesde — CHANGES_REQUESTED** [review]
So I gave it a quick try and noticed the following:

- If I don't type a state name, the error message isn't any helpful (but maybe that's restricted to the CLI argument parsing framework)
- The value of the option is called `TEXT`. There is no indication of what it means and what the possible values are.
- I just checked, and I can give that option an arbitrary value. So maybe make it optional with a sane default?
- You probably have renamed the option, the first commit shows an old name.

**Comment by meejah** [comment]
Great, thanks for taking a look .. I'll make some fix-ups (and yeah, on a second look it's not very apparent what one should pass to it ... I guess a good default would be "trace ALL the machines")

**Comment by meejah** [comment]
okay, made some fixups and re-worked it a little.

**Comment by meejah** [comment]
I re-worked this a bunch .. if you're interested in a second look, that'd be great @piegamesde

**Comment by piegamesde** [comment]
Sorry I can't test right now, but from the code documentation the change looks sane. I'd argue that using the full state machine names instead of one/two letter codes would be better, but I think I can see why you are doing this from a technical standpoint.

**Comment by meejah** [comment]
yeah .. honestly I don't really expect anyone to go beyond `--debug-state` (or at least: I haven't).
In general I agree about the names, but even in the code they're all referred to by those same one or two letters (`self._B.<whatever>` for example)...

**Pull request merged**
