### PR TITLE
ecosystem doc

### PR DESCRIPTION
**Pull request by meejah**
Making an attempt at summarizing the "state of the ecosystem" as it exists today.

### CODE REVIEW

**Review by vu3rdd — APPROVED** [review]
This looks very very nice!

**Comment by balejk** [comment]
@meejah There are several other applications which you could list:

* [Wormhole](https://gitlab.com/lukas-heiligenbrunner/wormhole) - an Android app; from what I have been able to find, the most feature-complete and actively developed (not available at F-Droid yet, which might be why you didn't list it, but [it's being worked on](https://gitlab.com/lukas-heiligenbrunner/wormhole/-/issues/17)); it uses the Rust library you list
* [Wormhole](https://f-droid.org/packages/com.pavelsof.wormhole/) - also Android; doesn't seem to be too actively developed; from what I remember, it's not too feature-complete, but it works for simple transfers; uses the Python library via Kivi
* [Wormhole William Mobile](https://github.com/psanford/wormhole-william-mobile) - Android/iOS app built on top of the Go library; basic features; it seems to be maintained
* [Rymdport](https://github.com/Jacalz/rymdport) - cross-platform graphical desktop application using wormhole-william; actively developed and feature complete; I have not used Warp yet so I cannot compare, but this is what I recommend to people who like to use GUI

Perhaps you could also add [link to the Go library](https://github.com/psanford/wormhole-william)?

Also there is a [tmux plugin](https://github.com/gcla/tmux-wormhole) and a [termshark integration](https://github.com/gcla/termshark/blob/e8a1ec6/docs/UserGuide.md?plain=1#L472), both built on top of wormhole-william.

**Comment by meejah** [comment]
Thanks @balejk I believe I have incorporated your suggestions, and improved some missing links .. thanks!

(Happy to accept more improvements etc if you have any)

**Comment by balejk** [comment]
@meejah Great, thank you for the additions. Just one small thing: you seem to have copied the wrong link for the Python library.

**Pull request merged**
