### PR TITLE
Add Chocolatey installation for Windows

### PR DESCRIPTION
**Pull request by sitiom**
See #397.

### CODE REVIEW

**Comment by guysoft** [comment]
Seems cool - why not add this?
Just looking at the repo and thought this might be worth a look.

**Comment by sitiom** [comment]
@guysoft This repo seems to be unmaintained now, new development has been happening in the [Rust port](https://github.com/magic-wormhole/magic-wormhole.rs).

**Comment by piegamesde** [comment]
For completeness, there is also a [Go port](https://github.com/psanford/wormhole-william) and it is equally active.

----

@meejah Do you happen to have commit access to this repository here?

**Comment by rollingmoai** [comment]
> @meejah Do you happen to have commit access to this repository here?

It's an unofficial port, so no.

**Comment by meejah** [comment]
@piegames yes I have commit here

**Comment by meejah** [comment]
As @warner is the only PyPI maintainer / release person I will defer to his judgement on this. 

I don't have a good way to evaluate whether this third-party repository is a reliable source of Windows releases.

**Comment by meejah** [comment]
I'm just going to merge this; regardless of what the readme says there _is_ a 0.12.0 in Chocolatey so :shrug: I guess it must be fine...? (/cc @warner)

**Comment by sitiom** [comment]
> This repo is not "abandoned"

So what's the status, development frozen?

**Comment by sitiom** [comment]
> moreover I am using the folder sending feature that is listed as missing in the rust port in this comment [#436 (comment)](https://github.com/magic-wormhole/magic-wormhole/pull/436#issuecomment-1207310013)

You might be interested in https://github.com/schollz/croc. I use that nowadays, and it works better for my everyday use.

**Comment by meejah** [comment]
> So what's the status, development frozen?

No, why do you believe that?

**Comment by sitiom** [comment]
There hasn't been any activity in this repo for the past year until the merging of this PR.

**Comment by meejah** [comment]
okay .. there are several other PRs newer than that (but, part of larger projects with implications for the server and the protocol repos).

**Pull request merged**
