### PR TITLE
Parse IPv6 address in TCP hint (--transit-helper argument)

### PR DESCRIPTION
**Pull request by FelisDiligens**
I tried pointing to my own transit-relay server by using `wormhole --transit-helper=tcp:[1111:2222:3333:4444:cccc:dddd:eeee:ffff]:4001 send "./example.file"`, however I got:
```
non-numeric port in TCP hint 'tcp:[1111:2222:3333:4444:cccc:dddd:eeee:ffff]:4001'
```

Not using brackets didn't work either:
```
non-numeric port in TCP hint 'tcp:1111:2222:3333:4444:cccc:dddd:eeee:ffff:4001'
```

I dug around and replaced a line in `parse_hint_argv` in file `_hints.py`.
Once parsing IPv6 addresses worked, I was able to use my transit-relay server to send/receive files over IPv6:

```
Sending (->relay:tcp:1111:2222:3333:4444:cccc:dddd:eeee:ffff:4001)..
100%|██████████████████████████████████████| 13.3k/13.3k [00:00<00:00, 5.00MB/s]
File sent.. waiting for confirmation
Confirmation received. Transfer complete.
```

(An IPv6 address has to be within square brackets, otherwise it isn't recognized.)

It might not be the most elegant solution to use a complicated regex string, but it does the trick. Hostnames, IPv4, and IPv6 addresses are recognized.

### CODE REVIEW

**Comment by piegamesde** [comment]
Thank you for bringing this up. I think the proper thing to do here is to use the proper URL syntax (`tcp://`) here, so that one could offload the parsing to a proper URL parsing library and get all those edge cases for free.

This can be done in a backwards compatible manner like this: [LeastAuthority/wormhole-william@`ab8635f` (#72)](https://github.com/LeastAuthority/wormhole-william/pull/72/commits/ab8635f703b5de3e7adb6cd5420774bccbcb7672)

**Comment by FelisDiligens** [comment]
I made another commit where it passes the parsing to Python's [urlparse](https://docs.python.org/3/library/urllib.parse.html) function, instead of doing the legwork itself.

It also removes 'priority=x.x' before parsing and is backwards-compatible to the old style urls.

I tested a few cases, it seems to work fine:
<details>
<summary>Test cases</summary>

```
# Works:
tcp:transit.magic-wormhole.io:8001
tcp://transit.magic-wormhole.io:8001
tcp:192.168.178.45:4001
tcp://192.168.178.45:4001
tcp:[2001:db8:3333:4444:5555:6666:7777:8888]:4001
tcp://[2001:db8:3333:4444:5555:6666:7777:8888]:4001
tcp://[2001:db8:3333:4444:5555:6666:7777:8888]:4001:priority=2.0
tcp:[::]:4001
tcp://[::]:4001
tcp:[::1]:4001
tcp://[::1]:4001
tcp:example.com:12345:priority=1.0
tcp://example.com:12345:priority=1.0

# Does not work:
tcp:
tcp:example.com
tcp:[2001:db8:3333:4444:5555:6666:7777:8888]
tcp:[2001:db8:3333:4444:5555:6666:7777:8888]:priority=1.0
tcp:2001:db8:3333:4444:5555:6666:7777:8888:4001
tcp::::4001
tcp:::1:4001
tcp://[2001:db8:3333:4444:5555:6666:7777:8888]:4001:priority=xyz
tor:something-something:8001
```

</details>

However, I didn't test it on Python 2.7.

**Comment by meejah** [comment]
It shouldn't need `//` to be a valid URL, lots of things don't (e.g. `mailto:`).

`tcp:` is kind of a weird scheme too (since its transport oriented), if we actually want these to be URLs (instead of transport-specific encodings) they should probably start with `transit:` or something (i.e. related to the actual protocol being spoken, not the transport).

**Comment by meejah** [comment]
In this case, since it _is_ a transport-specific option for a particular program, maybe `tcp6:...` or something makes sense? (And won't e.g. break existing usage like changing to `tcp://` will).

**Comment by meejah** [comment]
Yes, these are just details of this particular CLI implementation. So, the details of what particular URL parsing libraries accept shouldn't affect how the CLI is presented (especially because this _isn't_ a URL).

That said, care does need to be taken not to "bleed out" into the hints (that are sent in the protocol).

"tcp" versus "tcp6" tells the software how to use the information (and Twisted does have different endpoints for v4 versus v6). so `tcp:example.com` can then mean to contact "example.com" with a TCPv4 transport, while `tcp6:example.com` could mean to contact it with v6 transport (while e.g. `tcp6:1.1.1.1` doesn't make sense because it's a v4 address). For hostnames, it affects how you look them up (e.g. A versus AAAA records for example).

**Comment by meejah** [comment]
p.s. I'm actually surprised these _aren't_ Twisted "endpoint strings" since the v4 one looks like it would be a valid one (possibly minus the `priority=` part) ... and maybe they should be (this would mean `tcp6:...` would be the way to support v6 transports, but other things would come "for free" like Tor support by using `tor:...`).

**Comment by meejah** [comment]
> That said, care does need to be taken not to "bleed out" into the hints (that are sent in the protocol).

I just mean here that any peculiarities that this CLI has shouldn't be represented in the hints themselves (e.g. "`tcp6:`" isn't a well-known scheme etc). So, I meant that suggestion for this implementation (only) -- that is, `parse_hint_argv()` is already looking for the string `tcp:` so it could also accept `tcp6:` and treat that as a "must be v6 address" -- although see below about hostnames :)

We shouldn't actually have to care whether the thing is an IP address (of v4 or v6 flavour) or a proper hostname when sending the hint, or parsing it -- the "tcp" hint already has to support all those cases.

So this really is just a bug in https://github.com/magic-wormhole/magic-wormhole/blob/e522a3992217b433ac2c36543bf85c27a7226ed9/src/wormhole/_hints.py#L39 not accepting an IPv6 string properly. So, sorry for not reading the code more closely the first time :(

I think urlparse is probably overkill and maybe regex too? A hostname can't have `[` or `]` in it, right? So that could trigger the "parse this as ipv6, possibly with trailing port" parsing behavior...

**Comment by FelisDiligens** [comment]
Hi, again! Thanks for the quick answer. :)

I pushed two commits that only affect `parse_hint_argv` and `test_parse_hint_argv`.
It can now handle these cases:
```
tcp:[2001:0db8:85a3::8a2e:0370:7334]:1234
tcp6:[2001:0db8:85a3::8a2e:0370:7334]:1234
tcp6:host:1234
```
`tcp6:` is optional and `tcp:` accepts IPv6 addresses too.

It returns `None` in these cases:
```
tcp:[abc::xyz]:1234  # stderr: invalid IPv6 address in TCP hint 'tcp:[abc::xyz]:1234'
tcp6:[abc::xyz]:1234 # stderr: invalid IPv6 address in TCP hint 'tcp6:[abc::xyz]:1234'
tcp6:172.0.0.1:1234  # stderr: expected IPv6 address or hostname, got IPv4 address in TCP6 hint 'tcp6:172.0.0.1:1234'
```

Please let me know, if I missed anything.

**Comment by meejah** [comment]
Great, thanks for the quick follow-up.

It might be good to just get rid of `tcp6` entirely -- that was probably just noise on my part, confusing this with Twisted endpoints etc. :/ 

I don't think the user has any reason to care about that (right?) -- they just want it to work, and TCP is still TCP on v4 or v6...

**Comment by FelisDiligens** [comment]
> I don't think the user has any reason to care about that (right?) -- they just want it to work, and TCP is still TCP on v4 or v6...

I suppose, `tcp:` and `tcp6:` wouldn't make a difference here, so I think you're right. I removed `tcp6:` again and updated the tests.

**Comment by meejah** [comment]
great, thanks!

**Pull request merged**
